export const GET_DEVICE_LIST = 'GET_DEVICE_LIST';
export const RECEIVE_DEVICE_LIST = 'RECEIVE_DEVICE_LIST';

export const GET_DEVICE_INFO = 'GET_DEVICE_INFO';
export const RECEIVE_DEVICE_INFO = 'RECEIVE_DEVICE_INFO';

export const GET_DEVICE_VARIABLE = 'GET_DEVICE_VARIABLE';
export const RECEIVE_DEVICE_VARIABLE = 'RECEIVE_DEVICE_VARIABLE';

export const POST_DEVICE_FUNCTION = 'POST_DEVICE_FUNCTION';
export const RECEIVE_DEVICE_FUNCTION = 'RECEIVE_DEVICE_FUNCTION';